#' Perform imputation using Amelia package and EMB algorithm.
#'
#' @description Function use EMB (Expectation-Maximization with Bootstrapping ) to impute missing data. Function performance is highly depend from data structure and
#' chosen parameters.
#'
#'
#' @param df data.frame. Df to impute with column names and without target column.
#' @param col_type character vector. Vector containing column type names.
#' @param percent_of_missing numeric vector. Vector contatining percent of missing data in columns for example  c(0,1,0,0,11.3,..)
#' @param col_0_1 Decaid if add bonus column informing where imputation been done. 0 - value was in dataset, 1 - value was imputed. Default False. (Works only for returning one dataset).
#' @param parallel If true parallel calculation is used.
#' @param polytime parameter pass to amelia function
#' @param splinetime parameter pass to amelia finction
#' @param intercs parameter pass to amleia function
#' @param empir parameter pass to amelia function. If empir dont set empir=nrow(df)*0.015.
#' @param verbose If true function will print on console.
#' @param return_one Decide if one dataset or amelia object will be returned.
#' @param out_file  Output log file location if file already exists log message will be added. If NULL no log will be produced.
#' @param m Number of datasets generated by amelia. If retrun_one=TRUE first dataset will be given.
#' @import Amelia
#'
#' @return Return one data.frame with imputed values or amelia object.



autotune_Amelia <- function(df,col_type,percent_of_missing,col_0_1=FALSE,parallel=TRUE,polytime=NULL,splinetime=NULL,intercs=FALSE,
                            empir=NULL,verbose=FALSE,return_one=TRUE,m=3,out_file=NULL) {
  if(!is.null(out_file)){write('Amelia  ',file = out_file,append = T)}
  col_0_1 <- F

  if (sum(is.na(df))==0){return(df)}
  # prepering information about categorical column
  categorical_col <-  colnames(df)[ifelse(col_type=='factor',T,F)]
  if(length(categorical_col)==0){categorical_col <- NULL}

  # seting parallel options
  if(parallel){
    parallel <- 'multicore'
  }
  if( 'multicore'!=parallel){
    parallel <- 'no'
  }
  n_row <- length(df[,1])

  # Amelia Run
  tryCatch({
    if (is.null(empir) ){
      empir <- n_row*0.015
    }
    final <- Amelia::amelia(df,m=m,noms = categorical_col,parallel = parallel,p2s = as.numeric(verbose),empri = empir,polytime = polytime,splinetime = splinetime,intercs = intercs)
    if (return_one){
      for (i in final$imputations){
        if(!is.null(i)){
          final <- i
          break
          }
        }
    }
  # Avoiding situtation when amelia dont impute and dont throwe errors            c
  if(class(final)!='data.frame' & class(final)!='amelia'){
    stop('ERROR')
  }

  },error=function(e){
    if(!is.null(out_file)){
      write(as.character(e),file = out_file,append = T)
    }
    stop(e)
  })
  #adding 0_1 col
  if(col_0_1 & return_one){

      columns_with_missing <-  (as.data.frame(is.na(df))*1)[,percent_of_missing>0]
      colnames(columns_with_missing) <- paste(colnames(columns_with_missing),'where',sep='_')
      final <- cbind(final,columns_with_missing)

  }

  for (i in colnames(final)[col_type=='integer']){
    final[,i] <- as.integer(final[,i])
  }

  return(final)

}

