#' @title PipeOpAmelia
#'
#' @name PipeOpAmelia
#'
#' @description
#' Implements EMB methods as mlr3 pipeline more about amelia \code{\link{autotune_Amelia}}
#'
#' @section Input and Output Channels:
#' Input and output channels are inherited from \code{\link{PipeOpImpute}}.
#'
#'
#' @section Parameters:
#' The parameters are the parameters inherited from [`PipeOpImpute`], as well as: \cr
#' \itemize{
#' \item \code{id} :: \code{character(1)}\cr
#' Identifier of resulting object, default \code{"imput_Amelia"}.
#' \item \code{m} :: \code{integer(1)}\cr
#' Number of datasets generated by amelia, default \code{3}.
#' \item \code{polytime} :: \code{integer(1)}\cr
#' Integer between 0 and 3 indicating what power of polynomial should be included in the imputation model to account for the effects of time. A setting of 0 would indicate constant levels, 1 would indicate linear time effects, 2 would indicate squared effects, and 3 would indicate cubic time effects, default \code{NULL}.
#' \item \code{splinetime} :: \code{integer(1)}\cr
#' interger value of 0 or greater to control cubic smoothing splines of time. Values between 0 and 3 create a simple polynomial of time (identical to the polytime argument). Values k greater than 3 create a spline with an additional k-3 knotpoints, default \code{NULL}.
#' \item \code{intercs} :: \code{logical(1)}\cr
#' Method used if optimize=False. If NULL default method is used (more in methods_random section ), default \code{FALSE}.
#' \item \code{empir} :: \code{double(1)}\cr
#' Parameter pass to amelia function. If empir dont set  empir=nrow(df)*0.015, default \code{NULL}.
#' \item \code{parallel} :: \code{double(1)}\cr
#' If true parallel calculation is used, default \code{TRUE}.
#' \item \code{col_0_1} :: \code{logical(1)}\cr
#' 	Decaid if add bonus column informing where imputation been done. 0 - value was in dataset, 1 - value was imputed, Default \code{FALSE}.
#' \item \code{out_fill} :: \code{character(1)}\cr
#' Output log file location if file already exists log message will be added. If NULL no log will be produced, default \code{NULL}.
#'}
#'
#' @export

PipeOpAmelia <-  R6::R6Class("Amelia_imputation",lock_objects=FALSE,
                                 inherit = PipeOpImpute,  # inherit from PipeOp
                                 public = list(
                                   initialize = function(id = "imput_Amelia", col_0_1=FALSE,polytime=NULL,splinetime=NULL,intercs=FALSE,empir=NULL,m=3,parallel=TRUE,out_file
                                   ) {
                                     super$initialize(id, whole_task_dependent=TRUE,param_vals = list(col_0_1=col_0_1,polytime=polytime,splinetime=splinetime,intercs=intercs,empir=empir,m=m,parallel=parallel,out_file=out_file),
                                                      param_set= ParamSet$new(list(
                                                        'polytime'=ParamUty$new('polytime', default = NULL, tags = 'amelia'),
                                                        'splinetime'=ParamUty$new('splinetime',default = NULL,tags='amelia'),
                                                        'empir'=ParamUty$new('empir',default = NULL,tags='amelia'),
                                                        'parallel'=ParamLgl$new('parallel',default = TRUE,tags = 'amelia'),
                                                        'intercs'=ParamLgl$new('intercs',default = FALSE,tags='amelia'),
                                                        'col_0_1'=ParamLgl$new('col_0_1',default = F,tags='amelia'),
                                                        'm'=ParamInt$new('m',lower = 1,upper = Inf,default = 3,tags='amelia'),
                                                        'out_file'=ParamUty$new('out_file',default = NULL,tags = 'amelia')





                                                      ))
                                     )



                                     self$imputed <- FALSE
                                     self$column_counter <- NULL
                                     self$data_imputed <- NULL

                                   }),private=list(

                                     .train_imputer=function(feature, type, context){
                                       imp_function <- function(data_to_impute){




                                         data_to_impute <- as.data.frame(data_to_impute)
                                         # prepering arguments for function
                                         col_type <- 1:ncol(data_to_impute)
                                         for (i in col_type){
                                           col_type[i] <- class(data_to_impute[,i])
                                         }
                                         percent_of_missing <- 1:ncol(data_to_impute)
                                         for (i in percent_of_missing){
                                           percent_of_missing[i] <- (sum(is.na(data_to_impute[,i]))/length(data_to_impute[,1]))*100
                                         }
                                         col_miss <- colnames(data_to_impute)[percent_of_missing>0]
                                         col_no_miss <- colnames(data_to_impute)[percent_of_missing==0]

                                         data_imputed <- autotune_Amelia(data_to_impute,col_type,percent_of_missing,col_0_1 = self$param_set$values$col_0_1,
                                                                          parallel = self$param_set$values$parallel,polytime = self$param_set$values$polytime,
                                                                          splinetime = self$param_set$values$splinetime, intercs = self$param_set$values$intercs,
                                                                          empir = self$param_set$values$empir,m=self$param_set$values$m,optimize_empir = F,
                                                                         out_file= self$param_set$values$out_file)






                                         return(data_imputed)
                                       }
                                       self$imputed_predict <- TRUE
                                       self$flag <- 'train'
                                       if(!self$imputed){
                                         self$column_counter <- ncol(context)+1
                                         self$imputed <- TRUE
                                         data_to_impute <- cbind(feature,context)

                                         self$data_imputed <- imp_function(data_to_impute)
                                         colnames(self$data_imputed) <- self$state$context_cols

                                       }
                                       if(self$imputed){
                                         self$column_counter <- self$column_counter -1

                                       }
                                       if  (self$column_counter==0){
                                         self$imputed <- FALSE
                                       }
                                       self$train_s <- TRUE
                                       return(NULL)

                                     },
                                     .impute=function(feature, type, model, context){
                                       imp_function <- function(data_to_impute){


                                         data_to_impute <- as.data.frame(data_to_impute)
                                         # prepering arguments for function
                                         col_type <- 1:ncol(data_to_impute)
                                         for (i in col_type){
                                           col_type[i] <- class(data_to_impute[,i])
                                         }
                                         percent_of_missing <- 1:ncol(data_to_impute)
                                         for (i in percent_of_missing){
                                           percent_of_missing[i] <- (sum(is.na(data_to_impute[,i]))/length(data_to_impute[,1]))*100
                                         }
                                         col_miss <- colnames(data_to_impute)[percent_of_missing>0]
                                         col_no_miss <- colnames(data_to_impute)[percent_of_missing==0]

                                         data_imputed <- autotune_Amelia(data_to_impute,col_type,percent_of_missing,col_0_1 = self$param_set$values$col_0_1,
                                                                         parallel = self$param_set$values$parallel,polytime = self$param_set$values$polytime,
                                                                         splinetime = self$param_set$values$splinetime, intercs = self$param_set$values$intercs,
                                                                         empir = self$param_set$values$empir,m=self$param_set$values$m,optimize_empir = F,
                                                                         out_file=self$param_set$values$out_file)




                                         return(data_imputed)
                                       }
                                       if (self$imputed){
                                         feature <- self$data_imputed[,setdiff(colnames(self$data_imputed),colnames(context))]


                                       }
                                       if((nrow(self$data_imputed)!=nrow(context) | !self$train_s ) & self$flag=='train'){
                                         self$imputed_predict <- FALSE
                                         self$flag <- 'predict'
                                       }

                                       if(!self$imputed_predict){
                                         data_to_impute <- cbind(feature,context)

                                         self$data_imputed <- imp_function(data_to_impute)
                                         colnames(self$data_imputed)[1] <- setdiff(self$state$context_cols,colnames(context))
                                         self$imputed_predict <- TRUE
                                       }


                                       if (self$imputed_predict & self$flag=='predict' ){
                                         feature <- self$data_imputed[,setdiff(colnames(self$data_imputed),colnames(context))]

                                       }

                                       if(self$column_counter == 0 & self$flag=='train'){
                                         feature <- self$data_imputed[,setdiff(colnames(self$data_imputed),colnames(context))]
                                         self$flag=='predict'
                                         self$imputed_predict <- FALSE
                                       }
                                       self$train_s <- FALSE

                                       return(feature)
                                     }




                                 )
)

mlr_pipeops$add("Amelia_imputation", PipeOpAmelia)
